import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";
import { PersistentRouterTransport } from "../../src/router/persistent.js";
import type { RouterRun, RouterRunResult, RouterRunner } from "../../src/router/runner.js";

class FakeRunner implements RouterRunner { readonly runs: RouterRun[] = []; async run(request: RouterRun): Promise<RouterRunResult> { this.runs.push(request); const command = request.argv.join(" "); if ((command === "docker network inspect cyber26-router-8j3") || command === "docker inspect cyber26-openwrt-lab") return { exit_code: 1, stdout: "", stderr: "missing" }; if (command.includes("image inspect")) return { exit_code: 0, stdout: "sha256:537d90b97c6f0e99d3ced6af8c0dd1034370ee355ee00332bfa46935b843d767\n", stderr: "" }; if (command.includes("network inspect")) return { exit_code: 0, stdout: "true\n", stderr: "" }; if (command.includes("HostConfig.NetworkMode")) return { exit_code: 0, stdout: "cyber26-router-8j3 false unbound\n", stderr: "" }; if (command.includes("{{.Id}}")) return { exit_code: 0, stdout: "container-id\n", stderr: "" }; if (command.includes("sha256sum /etc/shadow")) return { exit_code: 0, stdout: "shadow-hash\n", stderr: "" }; return { exit_code: request.argv.some((part) => part.includes("dbclient")) ? 1 : 0, stdout: "", stderr: "Permission denied" }; } }
describe("persistent router transport", () => { test("uses only the fixed internal target and keeps seeded credentials out of argv", async () => { const directory = mkdtempSync(join(tmpdir(), "router-persistent-")); const runner = new FakeRunner(); try { const transport = new PersistentRouterTransport(runner, { now: () => "2026-10-09T20:00:00.000Z" }, directory); await transport.prepare(); const attempts = await transport.attack(); expect(attempts[0]?.outcome).toBe("rejected"); expect(runner.runs.some((run) => run.argv.includes("--internal"))).toBe(true); expect(runner.runs.filter((run) => run.argv.includes("dbclient")).every((run) => run.argv.includes("DROPBEAR_PASSWORD") && !run.argv.some((part) => part.startsWith("DROPBEAR_PASSWORD=")))).toBe(true); } finally { rmSync(directory, { recursive: true, force: true }); } }); });
